services:
  shard0:
    image: postgres:15-alpine
    container_name: shard0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myDb0
    volumes:
      - shard0_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./pg-conf/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - sharded_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  shard0-replica:
    image: postgres:15-alpine
    container_name: shard0-replica
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: replicatorpass
      POSTGRES_DB: myDb0R
    volumes:
      - shard0_replica_data:/var/lib/postgresql/data
    depends_on:
      shard0:
        condition: service_healthy
    networks:
      - sharded_network
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  shard1:
    image: postgres:15-alpine
    container_name: shard1
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myDb1
    volumes:
      - shard1_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./pg-conf/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - sharded_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  shard1-replica:
    image: postgres:15-alpine
    container_name: shard1-replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: replicatorpass
      POSTGRES_DB: myDb1R
    depends_on:
      shard1:
        condition: service_healthy
    volumes:
      - shard1_replica_data:/var/lib/postgresql/data
    networks:
      - sharded_network
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    

volumes:
  shard0_data:
  shard1_data:
  shard0_replica_data:
  shard1_replica_data:


networks:
  sharded_network:
    driver: bridge
